<ul class="breadcrumb">
    <li class="active">Users</li>
</ul>
<table class="table">
    <tr>
        <th>User Name</th>
        <th width="150px">Action</th>
    </tr>
    <?php foreach ($this->users as $user): ?>
        <tr>
            <td>
                <a href="<?php echo $this->url('application/user_projects', array(
                    'userName' => $user
                )) ?>"><?php echo $user ?></a>
            </td>
            <td>
                <a class="btn btn-primary btn-xs" href="<?php echo $this->url('application/user_projects', array(
                    'userName' => $user
                )) ?>">Projects</a>
                <a userName="<?php echo $user ?>" class="removeUser btn btn-danger btn-xs" href="<?php echo $this->url('application/remove_user_from_all_projects', array(
                    'backUrl' => base64_encode($this->serverUrl(true)),
                    'userName' => $user,
                ), null, true) ?>">Remove</a>
            </td>
        </tr>
    <?php endforeach ?>
</table>
<script>
    $(document).ready(function(){
        $('.removeUser').bind('click', function(){
            return confirm('Are you sure you want to remove user '+ $(this).attr('userName') +' from all projects?');
        });
    });
</script>